wearefuturegov/outpost

app/models/service.rb
Doesn't feel great - Like, in a way, all of the taxonomy fields should be ignored. It's actually the service_taxonomies we're interested in, isn't it? Cos that's what will change when a community user updates taxonomies. Think this would fix in short term but, but might need re-thinking.
=> Possible way to filter unwanted fields in comparison

app/models/service.rb, lib/tasks/process_permanent_deletions.rake, spec/models/service_spec.rb
When a service is destroyed, it's version history is destroyed with it. Therefore we don't want to create a version when we destroy it
=> Don't create a version on destroy

app/views/admin/ofsted/pending.html.erb, app/views/admin/requests/index.html.erb, app/views/shared/poppables/_organisation.html.erb
As per [user feedback](https://docs.google.com/spreadsheets/d/123YCOIITHivQGTronQYxvPfL4d-3snlo/edit#gid=2032181625&range=C17). There were a couple of other places we were truncating names and not showing a title, so I added titles to those too.
=> Add titles to truncated names so the full names appear on hover

app/controllers/feedback_controller.rb, spec/factories/service.rb, spec/factories/user.rb, spec/rails_helper.rb, spec/requests/suggesting_feedback_spec.rb
As per [user feedback](https://docs.google.com/spreadsheets/d/123YCOIITHivQGTronQYxvPfL4d-3snlo/edit#gid=2032181625&range=C15), we were redirecting admins who clicked 'Suggest an edit' in Scout (which opens the feedback form in Outpost) to their dashboard, instead of to the edit page of the service they came from. This fixes that.
As part of this I've added Devise helpers to our RSpec config, so that we can write nice RSpec tests involving logged in users 😄
=> Redirect admins to service edit page from the feedback form

app/models/service.rb, spec/models/service_spec.rb
We had a bug where if a user added a nested taxonomy and its parent to a new service they were creating, the `ServiceTaxonomy` for the child taxonomy was created correctly, but the one for the parent would be created without being associated to the service.
This PR fixes that - thanks @dtt101 for the solution! 🎉 
Side note - once this is merged & deployed, there's a manual cleanup task to go and delete all the `ServiceTaxonomies` that were created without a `service_id`.
=> Fix service taxonomy bug

lib/tasks/services/map_ofsted_setting_addresses_to_custom_fields.rake
Adds a rake task to map setting addresses from an Ofsted item to the linked service's custom fields. This enables admins to manage a service's setting address, which they currently can't do as Ofsted item addresses are fixed, and the service location addresses are managed by users, rather than admins.
=> Rake task for mapping Ofsted setting addresses to service custom fields

app/javascript/packs/warn-unsaved-changes.js
Fixes two bugs:
* Warn users about unsaved changes to select dropdowns
* Bug with Chrome ignoring the confirm dialog because of a missing `returnValue` (more info in [the `onbeforeunload` docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload))
I tried to test this behaviour with Cucumber and found that it's really hard to do! Browsers seem to handle `beforeunload` in different ways depending on whether they think the user has interacted with the page. So while this works for me in Firefox (and Chrome now too, with this fix), the same actions carried out using Capybara in a feature test in Firefox does not trigger the alert to pop up, even though the event fires.
We could unit test the JS, but I'm not sure that's really a valid approach since the tests …
=> Bug fix: warn users on unsaved changes

app/models/service.rb, app/models/taxonomy.rb, spec/models/service_spec.rb
Taxonomy counts way to high for top level taxonomies:
After a bit of debugging, it seems that every time a service was being saved, it was adding an extra top level service_taxonomy record for each second level taxonomy.
So for example, a service with "Clubs and groups", "Places to go" and "Activities for babies and toddlers" would get 3 new "Things to do" taxonomies every time it was saved. I would have thought that [this](https://github.com/wearefuturegov/outpost/blob/2757f237259da689f22ec447f9450d6f32eb0f57/app/models/service.rb#L47) would have solved, but apparently not. 
Changes committed here seem to resolve the issue, from some manual testing. Might need a rake task to clean up prod db too.
=> Fix taxonomy counter issue

app/serializers/indexed_services_serializer.rb
@userman123 I couldn't get the scope tagged with approach to work here so instead I'm just adding labels (only "Family Information Service", "Buckinghamshire Online Directory") 
but I can't work out how to rename these to bfis and bod when it goes into mongo.
[This was the closest solution I could find but it was erroring:](https://stackoverflow.com/questions/4137824/how-to-elegantly-rename-all-keys-in-a-hash-in-ruby)
```ages = { 'Bruce' => 32, 'Clark' => 28 }
mappings = { 'Bruce' => 'Bruce Wayne', 'Clark' => 'Clark Kent' }
ages.transform_keys(&mappings.method(:[]))
#=> { 'Bruce Wayne' => 32, 'Clark Kent' => 28 }```
I might have to come back to this section
=> Include specific labels in the mongodb

README.md
Adds some instructions about running the app with multiple directories. I know this is liable to change, but I think it's worth adding some light touch docs as we go 😄
=> Add multiple directories instructions to the README

app/controllers/api/v1/taxonomies_controller.rb
Small fix since I realised there was some dummy code in there still. Improved the error checking a bit too.
if `directory===valid label` it shows the taxonomies linked to it
if `directory!=valid label` it shows `{}`
if `no directory` it shows all taxonomies
however this functionality is probably a bit redundant for this install since when scout is deployed it builds a list of taxonomies from `/api/v1/taxonomy?dir=bod` but that list is only populated with ones that have a bod directory on them. If they add a new service that taxonomy wont appear on scout because its cached - or do we trigger a rebuild of scout (which I don't think we do)
=> better error checking for taxonomy filtering

app/controllers/api/v1/taxonomies_controller.rb
One more little fix - if theres no directories in the tags db then the taxonomies call errors - this will just set it to return {} if theres nothing in the tags column
=> if there are no db entries don't error

app/controllers/admin/requests_controller.rb
https://trello.com/c/2z4PCcc9/191-issue-bug-we-found-there-was-one-pending-service-in-the-bod-tab-however-when-we-clicked-on-pending-it-showed-all-the-pending-ser
The directory=blah filter wasn't applied on th epending page
=> Forgot to directory filter on requests!

lib/tasks/process_permanent_deletions.rake, spec/spec_helper.rb, spec/tasks/process_permanent_deletions_spec.rb
We haven't come to a solution for these users yet, but while we're working on a fix let's not have the whole rake task error when it encounters one of these users.
This PR also fixes the test file for the rake task which wasn't running due to a mistake in the filename, and adds DatabaseCleaner config for RSpec which should help make the rake task test more reliable.
=> Permanent deletions: don't error when there is a user with notes

app/controllers/admin/labels_controller.rb, app/models/service.rb, app/models/user.rb, app/views/admin/services/editors/_labels.html.erb
Currently on outpost we only show the most_used labels in filters, the labels page and within the add/edit page.
I'm not sure why this was done but this PR loads all labels where they are used. I suspect there will need to be some optimisation though. 
I think all the labels should be available everywhere since they're not tags even though they're used by acts as taggable, the only issue is looking through some of the data there are some misspelled or duplicate labels that have been created and lost to time that may need clearing out in the db (they have no services assigned to most of them that I can tell). Though if there hadn't have been most_used that issue may not have occurred.
=> show all labels alphabetically

app/assets/stylesheets/bucks-fis-design-library/_help-tips.scss, app/assets/stylesheets/bucks-fis-design-library/_layout.scss, app/views/admin/users/index.html.erb, spec/features/managing_users_spec.rb
Extended the actions class to let it be used without padding! Added a tippy icon for users marked for deletion - its not ideal as it should really be more obvious what it means but then theres too much text in the table.
=> Adds styling and some css changes for users marked for deletion

app/assets/stylesheets/bucks-fis-design-library/_globals.scss, app/assets/stylesheets/bucks-fis-design-library/_help-tips.scss, app/assets/stylesheets/bucks-fis-design-library/_layout.scss, app/controllers/admin/users_controller.rb, app/views/admin/users/index.html.erb, app/views/admin/users/show.html.erb, config/routes.rb, spec/features/managing_users_spec.rb
This PR fixes a bug where you could reactivate a user that had been marked for deletion, and they would remain marked for deletion (but they wouldn't get deleted because when we delete users we check that they are not active).
While I was there I also cleaned up the routes a bit.
It also adds the date when someone was marked for deletion to the users index page. This is because there has been a lot of confusion around when users have been marked for deletion (we didn't show this anywhere in Outpost until now) and when their deletion is meant to be processed (30 days later).
I am open to suggestions of how to style this better! 😄
=> Bugfixes: Users marked for deletion bugs

app/jobs/trigger_scout_rebuild_job.rb
If `.env` had 
```
SCOUT_BUILD_HOOK=
```
HTTParty would still post to the empty url causing errors in the logs.
=> Only trigger scout rebuild if hook is not empty

db/seeds.rb
Another small one but the lorum ipsum taxonomies all being one word just didn't sit right with me, have made it random between 1 and 5 now - a bit more natural 
I also kind of want to add subcategories too...
```ruby
taxonomy_ids = Taxonomy.last(10).map(&:id)
taxonomy_ids.each do | t |
rand(0...10).times do 
child_taxon = Taxonomy.create!({
name: Faker::Lorem.words(number: rand(1...5)).join(' ').capitalize,
parent_id: t
})
end
end
```
=> Taxonomies no longer just one word but variable

app/serializers/cost_option_serializer.rb, app/serializers/regular_schedule_serializer.rb, spec/factories/cost_option.rb, spec/serializers/cost_option_serializer_spec.rb, spec/serializers/regular_schedule_serializer_spec.rb
This fixes an issue with Open Referral UK compliancy, which requires us to include an ID with the regular schedules and cost options.
=> Add ids to regular schedule and cost option serializers
